version: '3'

services:
  landing-page:
    build: ./landing-page
    restart: unless-stopped
    networks:
      - web

  game:
    image: jump-game
    restart: unless-stopped
    networks:
      - web

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/ssl:/etc/nginx/ssl
      - ./landing-page:/var/www/landing-page
    restart: unless-stopped
    networks:
      - web
    depends_on:
      - landing-page
      - game

networks:
  web:
    driver: bridge
